---
title: "Homework 5"
author: "Arielle Glass"
date: "2024-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(ggplot2)
library(dplyr)
library(lubridate)
library(tidyverse)

```

```{r fig.width= 15, fig.height= 3}

data <- read.csv("../data/homicide-data.csv")

baltimore_data <- data %>%
  filter(city == "Baltimore") %>%
  mutate(date = ymd(reported_date),
          month = month(date),
          year = year(date))

monthly_data <- baltimore_data %>%
  group_by(year = year(date), month = month(date)) %>%
  summarize(homicides = n()) %>%
  ungroup() %>%
  mutate(
    date = make_date(year, month, 1),
    season = ifelse(month(month) %in% c(5:10), "Summer", "Winter"))

monthly_data %>%
  ggplot(aes(x = date, y = homicides)) +
  geom_bar(aes(fill= season), stat = "identity", position = "stack") +
  scale_fill_manual(values = c("Summer" = "lightgray", "Winter" = "lightblue")) + 
  geom_smooth(color = "blue", se = FALSE, size = 1, span= 0.1) +
  labs(x = "Date", y = "Monthly Homicides", fill = "Season") +
  ggtitle("Homicides in Baltimore, MD") +
  geom_vline(xintercept = as.Date("2015-04-12"), color = "red", linetype = "dashed", size = 1) +
  annotate("text", x = as.Date("2014-11-12"), y = 40, label = "Arrest of\nFreddie Gray", color = "white") +
  theme_dark() +
   theme(legend.position = "bottom")


```



